name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Ruby & Rust
        uses: jdx/mise-action@v4
      - name: Install dependencies
        run: bundle install
      - name: Run the default task
        run: bundle exec rake
